import { chromium } from "playwright";
const url = process.argv[2] || "http://localhost:3000";
const out = process.argv[3] || "/tmp/screenshot.png";
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 1280, height: 900 });
await page.goto(url, { waitUntil: "networkidle" });
await page.waitForTimeout(1000);
await page.screenshot({ path: out, fullPage: false });
await browser.close();
console.log("Screenshot:", out);
